### ISSUE TITLE
Lock posts on editing

### ISSUE THREAD

**Issue by karsasmus** [Leafpub/leafpub#109]
### This issue is for planning a write/edit lock of posts.

- If user A edits post X, user B should not be able to edit/update the post until user A finished editing OR is logged out.
- Lock status should be visible with an icon.
- Leafpub should create a view with locked posts for owner/admins to ensure it is possible to unlock a post
- a lock is saved in the database something like {`post_id`, `user_id`, `timestamp`}.

### Tasks
- [x] implement automated lock/unlock functionality, update models
- [x] update views to ensure lock icon is visible
- [x] create a database table `post_meta` to save lock data
