### ISSUE TITLE
Add a dashboard to Leafpub

### ISSUE THREAD

**Issue by karsasmus** [Leafpub/leafpub#110]
### This issue is for planning the dashboard

The dashboard can be your entry point after logging in to Leafpub instead of posts view.
It's an optional feature. You can enable/disable it via the setting's advanced tab. 

It is customizable with widgets. 
A widget is a Leafpub plugin that adds an element to the dashboard.

Widgets can be added via locater (`cmd + p`).
Widget's size and position can be changed with drag'n drop and is saved automatically to the database.

### Tasks
- [x] Add a model to interact with widgets
- [x] Add API endpoints to save the dashboard's layout, get a rendered widget
- [x] implement widgets
- [x] change redirect in `AdminController::dashboard`
